services:

  # FRONTEND 
  frontend:
    build: ./frontend     # Dockerfile está dentro de la carpeta frontend
    ports:
      - "8080:80"         # entro por 8080 y nginx responde por 80
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - todo-network


  # BACKEND
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - .env      # aquí se cargan las variables de la BD
    depends_on:
      - db
    networks:
      - todo-network


  # BASE DE DATOS
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Volumen para cargar el script de inicialización
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Volumen para que los datos no se borren
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todo-network


# VOLUMENES Y RED

volumes:
  postgres-data:


networks:
  # Red interna para que los contenedores se comuniquen
  # entre ellos usando sus nombres (backend, db, frontend)
  todo-network:
